services:

    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

    database:
        image: mysql:8.0
        ports:
            -   3307:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}  # Your database name
            - MYSQL_USER=${DB_USERNAME}       # Use a different username, not 'root'
            - MYSQL_PASSWORD=${DB_PASSWORD}    # Password for the new user
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} # Password for root
        volumes:
            -   db-data:/var/lib/mysql

volumes:
    db-data: ~
